---
name: Release
on:
  release:
    types: [published]

jobs:
  tests:
    uses: tuanalumi/hasura-storage/.github/workflows/test.yaml@main
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  build:
    needs: tests
    uses: tuanalumi/hasura-storage/.github/workflows/build-docker-image.yaml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
